scons.args: &scons
    scons_arg:
      - '--strict'
devices.gpio:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_GPIO=y
devices.adc:
    kconfig:
      - CONFIG_BSP_USING_SAADC=y
devices.flash:
    kconfig:
      - CONFIG_BSP_USING_ON_CHIP_FLASH=y
devices.i2c:
    kconfig:
      - CONFIG_BSP_USING_I2C=y
devices.spi:
    kconfig:
      - CONFIG_RT_USING_SPI=y
      - CONFIG_BSP_USING_SPI=y
devices.uart:
    kconfig:
      - CONFIG_BSP_USING_UART=y
devices.watchdog:
    kconfig:
      - CONFIG_BSP_USING_WDT=y
devices.qspi_flash:
    kconfig:
      - CONFIG_BSP_USING_QSPI_FLASH=y
devices.pwm:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
devices.rtc:
    kconfig:
      - CONFIG_BSP_USING_ONCHIP_RTC=y
devices.hwtimer:
    kconfig:
      - CONFIG_BSP_USING_TIM=y
      - CONFIG_BSP_USING_TIM0=y
# ------ NimBLE-v1.0.0 CI ------
nimble:
    kconfig:
      - CONFIG_BSP_USING_NIMBLE=y
      - CONFIG_PKG_USING_NIMBLE_V100=y
nimble.advertiser:
    <<: *scons
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_ADVERTISER=y
nimble.beacon:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_BEACON=y
nimble.blecsc:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_BLECSC=y
nimble.central:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_CENTRAL=y
nimble.ext.advertiser:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_EXT_ADVERTISER=y
      - CONFIG_PKG_NIMBLE_EXT_ADV=y
nimble.mesh:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_BLEMESH=y
nimble.per.hr:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_PER_HR=y
nimble.peripheral:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_PERIPHERAL=y
nimble.btshell:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_BTSHELL=y
nimble.uart:
    depends:
      - nimble
    kconfig:
      - CONFIG_PKG_NIMBLE_SAMPLE_BLEUART=y
# ------ SEGGER CI ------
segger:
    kconfig:
      - CONFIG_PKG_USING_SEGGER_RTT=y
      - CONFIG_RT_USING_SERIAL_V2=y
