scons.args: &scons
    scons_arg:
      - '--strict'

# ------ component CI ------
component.pwm:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
      - CONFIG_BSP_USING_PWM0=y

# ------ devices ------
devices.i2c:
    kconfig:
      - CONFIG_BSP_USING_HW_I2C=y
      - CONFIG_BSP_USING_HW_I2C0=y
      - CONFIG_BSP_HW_I2C0_PIN_PA2_PA3=y
      - CONFIG_BSP_HW_I2C0_CLK=100
      - CONFIG_BSP_USING_HW_I2C1=y
      - CONFIG_BSP_HW_I2C1_PIN_PB12_PB13=y
      - CONFIG_BSP_HW_I2C1_CLK=100

# ------ peripheral CI ------
peripheral.at24c02:
    kconfig:
      - CONFIG_RT_CONSOLEBUF_SIZE=256
      - CONFIG_RT_NAME_MAX=32
      - CONFIG_RT_USING_ULOG=y
      - CONFIG_ULOG_OUTPUT_LVL_D=y
      - CONFIG_ULOG_OUTPUT_LVL=7
      - CONFIG_ULOG_USING_ISR_LOG=y
      - CONFIG_ULOG_ASSERT_ENABLE=y
      - CONFIG_ULOG_LINE_BUF_SIZE=128
      - CONFIG_ULOG_USING_COLOR=y
      - CONFIG_ULOG_OUTPUT_TIME=y
      - CONFIG_ULOG_OUTPUT_LEVEL=y
      - CONFIG_ULOG_OUTPUT_TAG=y
      - CONFIG_ULOG_BACKEND_USING_CONSOLE=y
      - CONFIG_RT_USING_UTEST=y
      - CONFIG_UTEST_THR_STACK_SIZE=4096
      - CONFIG_UTEST_THR_PRIORITY=20
      - CONFIG_RT_UTEST_MAX_OPTIONS=64
      - CONFIG_PKG_USING_AT24CXX=y
      - CONFIG_PKG_AT24CXX_PATH="/packages/peripherals/at24cxx"
      - CONFIG_PKG_AT24CXX_EE_TYPE_AT24C02=y
      - CONFIG_PKG_AT24CXX_EE_TYPE=1
      - CONFIG_PKG_USING_AT24CXX_LATEST_VERSION=y
      - CONFIG_PKG_AT24CXX_VER="latest"
      - CONFIG_BSP_USING_AT24C02=y
      - CONFIG_BSP_USING_AT24C02_UTEST=y
      - CONFIG_RT_USING_I2C=y
      - CONFIG_RT_USING_I2C_BITOPS=y
      - CONFIG_BSP_USING_HW_I2C=y
      - CONFIG_BSP_USING_HW_I2C0=y
      - CONFIG_BSP_HW_I2C0_PIN_PA2_PA3=y
      - CONFIG_BSP_HW_I2C0_CLK=100