[package]
name = "em_thread"
version = "0.1.0"
edition = "2021"

[lib]
name = "em_thread"
crate-type = ["staticlib"]

[dependencies]
rt-rust = { path = "../../../core" }
rt_macros = { path = "../../../rt_macros" }
