name: Check Spelling

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    if: github.repository_owner == 'RT-Thread'
    permissions:
      contents: read
      pull-requests: read
      actions: read
    steps:
    - name: output ignore words info
      run: |
        echo "> If any words shown as incorrect are spelled correctly, please add them to .github/actions/spelling/allow.txt." >> $GITHUB_STEP_SUMMARY
    - name: check spelling
      id: spelling
      uses: check-spelling/check-spelling@prerelease
      with:
        checkout: true
        check_file_names: 0
        only_check_changed_files: 1
        post_comment: 0
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
    - name: output Success info
      run: |
        echo "âœ… Check spelling success." >> $GITHUB_STEP_SUMMARY
